name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  win32: ^5.0.9
  path_provider: ^2.1.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 


flutter:
  uses-material-design: true
  assets:
    - assets/images/
